services: mongodb
language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - jruby-19mode
  - jruby-head

gemfile:
  - Gemfile
  - gemfiles/mongoid-4.0.gemfile

matrix:
  allow_failures:
    - rvm: jruby-head
